import React from 'react';
import Particle from '../particles/Particle';
import Footer from '../footer/Footer';

const Condition = () => {
    return (
        <div className="l-condition">
            <div className="condition max-content container">
                <div className="parallax">
                    <div className="parallax-slide"></div>
                    <Particle />
                </div>
                <h2 className="condition-title">AlyCoin<span>Terminos y condiciones</span></h2>
                <p className="condition-paragraph">Bienvenido a <span>AlyCoin</span>, “Una moneda para el mundo”. La plataforma de Internet y los servicios son ofrecidos por Ecosistema <span>AlyCoin</span>. Al utilizar nuestro sitio web, productos y servicios, usted acepta explícitamente estos Términos de uso como parte del contrato del usuario a través de la plataforma de Internet.</p>
                <p className="condition-paragraph">Nos reservamos el derecho de actualizar estos Términos de uso cuando se amerite. Dichos cambios son inmediatamente aplicables, tan pronto como se publiquen en el sitio web. Es su responsabilidad revisar estos Términos de uso regularmente.</p>
                <h3 className="condition-subtitle">1. Objeto del contrato.</h3>
                <p className="condition-paragraph">(1) <span>AlyCoin</span> es una empresa descentralizada de aplicaciones para la usabilidad de criptomonedas, donde también cuenta con su propia criptomoneda <span>AlyCoin</span>, creado bajo la red de ethereum de token ERC20 la compañía contara con un ecosistema innovador en el campo de los servicios y/o productos digitales que impulsará la usabilidad de la criptomoneda. Estos productos se conocerán como <span>AlyExecutive</span>, <span>AlySocial</span>, <span>AlyShopping</span>, <span>AlyPay</span> y <span>CupON</span> (tan pronto como estén disponible). Además, <span>AlyCoin</span> tendrá su fundación de ayuda social, la cual se denominará <span>AlyFundation</span>, en la que podrás realizar tus donaciones.</p>
                <p className="condition-paragraph">(2) La compañía de <span>AlyCoin</span>, le ofrece a usted, como usuario de cualquier producto del ecosistema de <span>AlyCoin</span> y de la misma criptomoneda, un servicio de soporte en línea gratuito, mediante el cual puede realizar diferentes consultas respecto al funcionamiento de los servicios del ecosistema de <span>AlyCoin</span> o información sobre la criptomoneda <span>AlyCoin</span>. Puede ver los productos con cargo de <span>AlyCoin</span> aquí, para realizar sus compras de criptomonedas AlyCoin. Además, también puede registrarse como <span>AlyExecutive</span> (AGENTE DE VENTAS INDEPENDIENTE (AVI) <span>AlyCoin</span>) para iniciar una actividad de ventas de paquetes de <span>AlyCoin</span>.</p>
                <p className="condition-paragraph">Se le informará por separado sobre el contenido del pedido imputable respectivo, los precios y las condiciones de pago antes de solicitar un producto imputable o cualquier otra conclusión de una relación contractual imputable. Al hacer clic en el botón "Comprar", expresa su voluntad de celebrar un contrato sobre el servicio o los bienes con cargo a su cargo que usted haya seleccionado. La relación contractual se establece luego con la confirmación por correo electrónico de la orden por parte de <span>AlyCoin</span>.</p>
                <h4 className="condition-subtitle">2. Registro en el sitio web de <span>AlyCoin</span></h4>
                <p className="condition-paragraph">(1) Antes de poder aprovechar las ofertas y servicios de <span>AlyCoin</span>, debe registrarse en el sitio web como primer paso. La inscripción es gratuita. Los datos requeridos para el registro o más tarde para completar el registro deben ser completos y verdaderos.</p>
                <p className="condition-paragraph">(2) Al iniciar sesión, debe ingresar su dirección de correo electrónico, usuario y seleccionar una contraseña. Al hacer clic en el botón "Registro gratuito", declara que desea celebrar un contrato de usuario para el uso gratuito de la plataforma de Internet. La relación contractual se establece con la conformación de correo electrónico del registro por parte de <span>AlyCoin</span>, que incluye los datos de acceso. Después de recibir los datos de acceso, puede crear su perfil en el sitio web y acceder a cualquiera de los paquetes de <span>AlyCoin</span> que desea comprar.</p>
                <p className="condition-paragraph">Se celebra un contrato con personas jurídicas, empresas privadas o personas físicas que hayan cumplido 18 años (o la edad necesaria para la celebración de contratos efectivos en el país de residencia).</p>
                <p className="condition-paragraph">(3) Usted asume toda la responsabilidad por la legalidad y la exactitud de los datos especificados en el momento del registro.</p>
                <p className="condition-paragraph">(4) La intención deliberada y / o fraudulenta puede resultar en una acción civil. <span>AlyCoin</span> también se reserva el derecho de bloquear los perfiles y las cuentas de los usuarios, que han proporcionado información falsa de forma deliberada o fraudulenta y de ejercer la rescisión extraordinaria del contrato del usuario.</p>
                <p className="condition-paragraph">(5) Solo puedes crear un perfil. Los usuarios registrados no pueden iniciar sesión como nuevo cliente o registrarse nuevamente especificando una nueva dirección de correo electrónico. Si un usuario ha creado múltiples perfiles, entonces debe decidir por un solo perfil. Todos los demás perfiles serán eliminados por <span>AlyCoin</span>. La creación de múltiples perfiles es una razón importante para un bloqueo permanente del usuario sin previo aviso.</p>
                <p className="condition-paragraph">(6) Al realizar algún cambio en sus datos de usuario y dirección de correo electrónico, <span>AlyCoin</span> le enviará un pin de confirmación a través de su correo electrónico actualmente registrado para verificar la legitimidad de la acción que está realizando dentro de la plataforma de <span>AlyCoin</span>.</p>
                <p className="condition-paragraph">(7) No puede permitir que ningún tercero use su perfil y datos de acceso. El uso de su cuenta por un tercero se considera una razón importante para el bloqueo permanente del usuario sin previo aviso. Es de su propio interés informar a <span>AlyCoin</span> de inmediato sobre cada intento de acceso realizado por un tercero y todo mal uso de su cuenta en línea.</p>
                <p className="condition-paragraph">(8) Mientras se registra, puede seleccionar un nombre de usuario y una contraseña de su elección. Usted se compromete a mantener el secreto con respecto a la contraseña. Si nota un uso no autorizado de su contraseña, debe informar de inmediato a <span>AlyCoin</span> a support@alycoin.me. Si olvida su contraseña, puede restablecerla con la ayuda del procedimiento de restablecimiento proporcionado (correo electrónico a la dirección de correo electrónico especificada por usted).</p>
                <p className="condition-paragraph">(9) <span>AlyCoin</span> se reserva el derecho de rechazar registros a su propia discreción y con cualquier razón que lo especifique. Si <span>AlyCoin</span> rechaza su registro, todas las cantidades que haya transferido al procesador de pagos le serán devueltas dentro de las seis semanas.</p>
                <h5 className="condition-subtitle">3. Obligaciones del cliente.</h5>
                <p className="condition-paragraph">(1) Se le prohíbe violar los derechos de terceros, acosar a terceros o violar la ley o violar la buena moral al usar los servicios de <span>AlyCoin</span> en Internet. Usted está particularmente comprometido a abstenerse de las siguientes acciones:</p>
                <p className="condition-paragraph">• Declaraciones circulantes con contenido insultante, irritante, abusivo, violento, inflamatorio, sexista, obsceno, pornográfico, racista, moralmente censurable o chocante o prohibido. </p>
                <p className="condition-paragraph">• Insultar, acosar, amenazar, atemorizar, difamar, avergonzar a otros clientes, empleados o promotores de ventas (<span>AlyExecutive</span>) de <span>AlyCoin</span></p>
                <p className="condition-paragraph">• Espiar, reenviar o difundir información personal o confidencial de otros clientes, promotores de ventas (AlyExecutive) o empleados de <span>AlyCoin</span> u otra violación de la privacidad de otros clientes, promotores de ventas (AlyExecutive) o empleados de <span>AlyCoin</span></p>                                    
                <p className="condition-paragraph">• Declaraciones falsas circulantes sobre raza, religión, sexo, orientación sexual, fuente, posición social de otros clientes, empleados o promotores de ventas (AlyExecutive) de <span>AlyCoin</span></p>
                <p className="condition-paragraph">• Espiar, reenviar o difundir información confidencial de <span>AlyCoin</span></p>                                    
                <p className="condition-paragraph">• Falsas afirmaciones circulantes sobre <span>AlyCoin</span></p>                                    
                <p className="condition-paragraph">• Pretendiendo ser un empleado de <span>AlyCoin</span> o una compañía afiliada o socio de <span>AlyCoin</span></p>                                    
                <p className="condition-paragraph">• Uso de imágenes, fotos, gráficos, videos, piezas musicales, sonidos, textos, marcas, títulos, nombres, software u otros contenidos y letreros legalmente protegidos sin la aprobación del titular de los derechos de autor o permiso a través de un contrato, reglamento o especificación legal</p>                                    
                <p className="condition-paragraph">• Circulación de comentarios con contenido publicitario, religioso o político.</p>                                    
                <p className="condition-paragraph">• Usar contenidos prohibidos o ilegales</p>                                    
                <p className="condition-paragraph">• Explotación de errores en la programación (llamados Bugs)</p>                                    
                <p className="condition-paragraph">• Llevar a cabo medidas que conduzcan a una carga irrazonable en el servidor y/o pueden perjudicar masivamente el proceso para otros clientes</p>                                    
                <p className="condition-paragraph">• Piratear o craquear y apoyar o incitar a la piratería o craqueo</p>                                    
                <p className="condition-paragraph">• Distribuir software falso y apoyar o incitar software falso</p>                                    
                <p className="condition-paragraph">• Cargar archivos que contengan virus, troyanos, gusanos o datos corruptos</p>                                    
                <p className="condition-paragraph">• Usar o distribuir programas de software “Auto”, programas de software “Macro” u otros programas de software de “utilidad de trucos”</p>                                    
                <p className="condition-paragraph">• Modificación de servicios o partes de la misma</p>                                    
                <p className="condition-paragraph">• Interrumpir las transferencias desde y hacia los servidores de la oficina y el servidor del sitio web</p>                                    
                <p className="condition-paragraph">• Intrusión en servidores de oficina, servidores de datos o servidores web.</p>                                     
                <p className="condition-paragraph">(2) <span>AlyCoin</span> se reserva el derecho de bloqueo inmediato y terminación extraordinaria de la cuenta en línea y del contrato del usuario, en la medida en que las obligaciones reguladas en (1) o la ley aplicable sean las siguientes. Violada con respecto al uso.</p>
                <h6 className="condition-subtitle">4. Terminación del contrato</h6>
                <p className="condition-paragraph">(1) <span>AlyCoin</span> puede rescindir el contrato del usuario y bloquear su perfil en cualquier momento sin previo aviso, si existe una causa importante que justifique una terminación extraordinaria inmediata sin previo aviso. Las siguientes constituyen las causas importantes que son aplicables como causas importantes:</p>
                <p className="condition-paragraph">• Violación particularmente grave de los Términos de uso</p>
                <p className="condition-paragraph">• Actividades ilegales fraudulentas o de otro tipo especialmente importantes con respecto al uso de cada uno de los productos del ecosistema de <span>AlyCoin</span>.</p>
                <p className="condition-paragraph">• Suministro de información falsa y engañosa a <span>AlyCoin</span></p>
                <p className="condition-paragraph">• Uso fraudulento, uso ilegal o cualquier otro uso indebido de la criptomoneda <span>AlyCoin</span>.</p>
                <p className="condition-paragraph">• Distribución, copia, publicación u otro uso o procesamiento no autorizado de materiales de capacitación (p. Ej., Carga en Youtube, etc.)</p>
                <p className="condition-paragraph">• Promover paquetes de <span>AlyCoin</span> y/o servicios del ecosistema de <span>AlyCoin</span> a un precio diferente del establecido por <span>AlyCoin</span>.</p>
                <p className="condition-paragraph">• Causar daños y pérdidas de todo tipo con respecto a <span>AlyCoin</span> u otros clientes o promotores de ventas (<span>AlyExecutive</span>) de <span>AlyCoin</span>.</p>
                <p className="condition-paragraph">(2) Usted puede rescindir su contrato de usuario en cualquier momento, por lo que enviar la terminación ordinaria por correo electrónico a support@alycoin.me es suficiente para el acceso efectivo de la terminación y la eliminación de su perfil en la Comunidad y el Ecosistema de <span>AlyCoin</span> en cualquier momento.</p>
                <h6 className="condition-subtitle">5. Disponibilidad del servidor</h6>
                <p className="condition-paragraph"><span>AlyCoin</span> está disponible 24 x 7 con una disponibilidad del promedio anual del 97.5%. El tiempo de inactividad debido al mantenimiento y las actualizaciones de software y los períodos en los que no se puede acceder al servicio a través de Internet debido a problemas técnicos o de otro tipo que no están bajo el control de <span>AlyCoin</span> (fuerza mayor, negligencia de terceros, etc.) están excluidos de este . Para poder utilizar los servicios de <span>AlyCoin</span> por completo, debe usar las tecnologías más recientes (de navegador) para permitir su uso en su computadora y/o móvil (por ejemplo, activación de Java Script, cookies, ventanas emergentes). Es posible que, al usar tecnologías más antiguas o poco comunes, tenga algunas limitaciones para acceder a los servicios de <span>AlyCoin</span>.</p>
                <h6 className="condition-subtitle">6. Exclusión de responsabilidad</h6>
                <h6 className="condition-subtitle-diff">AVISO DE RIESGO PARA CLIENTES Y SOCIOS DE VENTAS.</h6>
                <p className="condition-paragraph">Antes de que decida utilizar los servicios de <span>AlyCoin</span>, se compromete a tomar nota de la siguiendo los avisos de riesgo y la exclusión de responsabilidad, y aceptarlos como un componente del contrato.</p>
                <p className="condition-paragraph">Usted reconoce y acepta explícitamente las siguientes disposiciones al poner una marca de verificación, como componente del contrato, antes del uso del portal de Internet y la conclusión de un contrato de compra o distribución con <span>AlyCoin</span>:</p>
                <p className="condition-paragraph">(1) Usted reconoce explícitamente que <span>AlyCoin</span> no ofrece ninguna inversión financiera, activos u otras inversiones financieras o instrumentos financieros directos o indirectos. Por el contrario, <span>AlyCoin</span> proporciona paquetes con tokens de la moneda para sus clientes y proporciona a sus clientes un backoffice especialmente desarrollado para el control y contabilidad de las mismas, además de servicios adicionales, y <span>AlyCoin</span> también proporcionará Productos de software sofisticados como aplicaciones para incrementar el valor de los tokens.</p>
                <p className="condition-paragraph">(2) Usted reconoce y acepta que <span>AlyCoin</span> no vende ni distribuye ni adquiere monedas criptográficas directa o indirectamente o a través de terceros. Además, reconoce y acepta que tiene plena claridad y está adecuadamente informado e informada de que el mercado de las monedas criptográficas es altamente VOLÁTIL y este mercado es, al mismo tiempo, EXTREMADAMENTE ESPECULATIVO y conlleva un riesgo significativo de pérdida en la acuñación, en la posesión o comercialización de monedas criptográficas, lo que puede llevar a una pérdida considerable y en el peor de los casos, a una PÉRDIDA TOTAL del valor de las monedas criptográficas “ganadas” o adquiridas de otro cualquier modo.</p>
                <p className="condition-paragraph">(3) Usted reconoce y acepta explícitamente que no existen garantías, o promesas de ningún tipo sobre proyecciones de ganancias, desarrollos de precios u otros ingresos relacionados con las monedas criptográficas “ganadas” o poseídas o adquiridas por <span>AlyCoin</span>, y todas las declaraciones. y los comentarios de <span>AlyCoin</span> o sus socios de ventas con respecto a esto deben considerarse meramente como expresiones de opinión y no como garantía de ganacias.</p>
                <p className="condition-paragraph">(4) Usted reconoce y acepta explícitamente, particularmente antes de la conclusión del contrato de compra, que usted es una persona experimentada en el campo de las monedas criptográficas, las inversiones de monedas criptográficas y el comercio de monedas criptográficas.</p>
                <p className="condition-paragraph">(a) Usted entiende explícitamente que está preparado para asumir los riesgos financieros, legales, relacionados con los impuestos y otros riesgos relacionados con sus monedas criptográficas adquiridas.</p>
                <p className="condition-paragraph">(b) Usted está financieramente en condiciones de soportar la pérdida de sus inversiones totales en el marco de la disponibilidad del contrato de compra y otros servicios de <span>AlyCoin</span> teniendo en cuenta sus condiciones financieras personales y recursos financieros, su estilo de vida personal y sus obligaciones monetarias, sin afectar su estado financiero en caso de una pérdida total considerable del valor de sus monedas criptográficas de manera sustancial.</p>
                <p className="condition-paragraph">(c) Usted tiene conocimiento sobre las respectivas monedas criptográficas y sus factores determinantes del valor, que ha extraído por usted mismo o que posee de otra manera.</p>
                <p className="condition-paragraph">(5) Usted reconoce y acepta explícitamente que <span>AlyCoin</span> no le ofrece ningún consejo con respecto a las monedas criptográficas, los mercados de monedas criptográficas, otros mercados financieros, productos de inversión, activos subyacentes y mercados o recomendaciones de inversión de ningún tipo, sino todo lo contrario, <span>AlyCoin</span> Proporcionará materiales de capacitación general con referencia a las monedas criptográficas, los mercados de monedas criptográficas y la minería.</p>
                <p className="condition-paragraph">(6) Usted reconoce y acepta explícitamente que es posible en el marco de leyes, puntos de vista gubernamentales o jurisdicción de acuerdo con sus leyes nacionales, que la acuñación, posesión o comercio de crypto coin no está legalmente permitido o solo está legalmente permitido con autorización y es su exclusiva responsabilidad garantizar que el uso de los servicios de <span>AlyCoin</span> esté permitido según la ley pertinente para usted.</p>
                <p className="condition-paragraph">(7) Usted reconoce y acepta explícitamente que los pagos de cualquier tipo son voluntarios en relación con los servicios acordados por contrato de <span>AlyCoin</span> y existen sin ningún reclamo legal. En particular, usted acepta explícitamente que acepta todos los resultados de la moneda criptográfica obtenida por la acuñación y que las ganancias se basan en el rendimiento de la moneda criptográfica obtenida de esta manera y otros posibles resultados positivos o negativos con respecto a las monedas criptográficas obtenidas y que surgen en relación con la disponibilidad de los servicios de <span>AlyCoin</span> los cuales podrían ser muy diferentes o pueden no ocurrir en absoluto, ya que dependen de un gran número de factores y variables imprevistos. </p>
                <p className="condition-paragraph">(8) Usted reconoce y acepta explícitamente que las declaraciones, pronósticos falsos, especulativos o inversión financiera, que se utilizan para promover el procesamiento y uso de los servicios de <span>AlyCoin</span> están estrictamente prohibidos.</p>
                <p className="condition-paragraph">(9) Usted reconoce y acepta explícitamente que <span>AlyCoin</span> rechaza explícitamente todas las declaraciones de terceros sobre sus servicios y estos no son bienvenidos y <span>AlyCoin</span> aconseja a sus clientes que no confíen en las declaraciones de terceros, que se refieren a los resultados, ganancias y las experiencias relacionadas con los servicios de <span>AlyCoin</span>, como la acuñación, posesión o comercialización de monedas criptográficas, ya sean positivas o negativas, ya que dichos resultados no se pueden duplicar de un usuario a otro o de una moneda criptográfica a otra.</p>
                <p className="condition-paragraph">(10) Debido a los altos riesgos asociados a la inversión, posesión o comercialización que la moneda de criptográfica representada en las paras (1) a (5) y (7) a (9), <span>AlyCoin</span>  no proporciona ninguna explicitas o garantías implícitas y no hace ningún acuerdo de responsabilidad, que los clientes alcancen un beneficio, o que los clientes no incurren ninguna pérdida o pérdida total. Queda bajo responsabilidad del usuario saber si la comercialización de monedas de criptografía es legalmente permitida en su país de residencia.</p>
                <p className="condition-paragraph">(11) Usted reconoce y acepta explícitamente que <span>AlyCoin</span> en vista de la volatilidad y la naturaleza extremadamente fluctuante de los mercados de monedas criptográficas, está autorizado para restringir o finalizar sus servicios total o parcialmente para mercados individuales en cualquier momento sin previo aviso para el caso, causando una pérdida importante en el valor de la moneda criptográfica como también se basa en las declaraciones de la sección (6) y está autorizado para una terminación extraordinaria sin previo aviso de la relación contractual con usted.</p>
                <h6 className="condition-subtitle-diff">II. AVISO DE RIESGO ADICIONAL PARA EL SOCIO DE VENTAS INDEPENDIENTE</h6>
                <p className="condition-paragraph">(1) Usted reconoce explícitamente que los avisos de riesgo mencionados en I, la exclusión de responsabilidad y el derecho excepcional de rescisión también son aplicables para usted, siempre que el registro no se realice como cliente, sino como socio de ventas, en la medida en que se encuentre, al mismo tiempo, el cliente de <span>AlyCoin</span>.</p>
                <p className="condition-paragraph">(2) Usted reconoce y acepta explícitamente que, aparte de las regulaciones contractuales como socio de ventas de <span>AlyCoin</span>, no hay garantías o compromisos de ningún tipo con respecto a las oportunidades de ingresos, posibilidades de distribución de beneficios, expectativas de comisiones u otras bonificaciones, ingresos o ingresos de cualquier, los riesgos son asumidos o pueden ser asumidos.</p>
                <p className="condition-paragraph">(3) Usted reconoce y acepta explícitamente que los posibles dividendos, comisiones u otras bonificaciones que se produzcan, son puramente voluntarios, quizás por servicios acordados en el contrato de <span>AlyCoin</span>.</p>
                <p className="condition-paragraph">(4) Usted reconoce y acepta explícitamente que todos los ejemplos de ganancias o ingresos y también los posibles resultados, que pueden ocurrir en relación con la venta de bienes, por ejemplo, al recibir las comisiones de ellos, deben entenderse exclusivamente como ejemplos de ejemplos, suposiciones. y / o estimaciones y no se pueden entender en absoluto como expectativas de comisión obvias o probables, y mucho menos como comisiones u otras garantías de ganancias o promesas. La comisión u otros ingresos que pueden esperarse en realidad pueden variar severamente o no ocurrir, o ocurrir en una medida limitada, ya que dependen de la gran cantidad de factores y variables personales y económicos imprevistos.</p>
                <p className="condition-paragraph">(5) Usted reconoce y acepta explícitamente que, sobre la base de los dividendos, comisiones u otros ingresos anteriores, no hay proyecciones o reclamos sobre el desarrollo futuro, ya que incluso estos dependen de un gran número de factores y variables imprevistos en términos  (4) .</p>
                <p className="condition-paragraph">(6) <span>AlyCoin</span> le desalienta explícitamente que base sus decisiones sobre la actividad de ventas de <span>AlyCoin</span> en los dividendos, comisiones u otros ingresos declarados por terceros y se refiera a las comisiones u otros ingresos supuestamente generados por otros socios de ventas de <span>AlyCoin</span>, como este tipo de publicidad de la actividad de ventas de <span>AlyCoin</span> está estrictamente prohibido para cada socio de ventas de acuerdo con las especificaciones contractuales, particularmente porque las comisiones ganadas de un socio de ventas no se pueden comparar, copiar o reflejar con los resultados esperados de otro socio de ventas.</p>
                <h6 className="contition-subtitle">III. COMPONENTE DE CONTRATO</h6>
                <p className="condition-paragraph">De acuerdo con los avisos de riesgo indicados en los puntos I. y II. La exclusión de responsabilidad y el derecho especial de rescisión (solo en virtud de I.) usted reconoce y acepta explícitamente ahora mediante una marca de verificación, antes del uso del portal de Internet de <span>AlyCoin</span>, de que conoce los riesgos mencionados anteriormente en I. y II y también del derecho especial de rescisión bajo I. y acepta explícitamente el mismo como un componente del contrato.</p>
                <h6 className="condition-subtitle-diff">OTROS RIESGOS</h6>
                <p className="condition-paragraph">(1) <span>AlyCoin</span> no se responsabiliza en el uso de estas aplicaciones en los países como Estados Unidos de América, Brasil, Canadá, México o los Emiratos Árabes Unidos, como compañía está prohibido realizar algún tipo de trabajo que tenga que ver con <span>AlyCoin</span> en los países mencionados.</p>
                <p className="condition-paragraph">(2) <span>AlyCoin</span> no se hace responsable de la información falsa en su registro. En consecuencia, <span>AlyCoin</span> no puede asumir la responsabilidad de la exactitud de esta información y sus contenidos guardados en <span>AlyCoin</span>. </p>
                <p className="condition-paragraph">(3) Además, con referencia al aviso de riesgo, <span>AlyCoin</span> no es responsable del logro del resultado deseado, que el cliente desea lograr mediante el uso de la plataforma de Internet y los productos del ecosistema de <span>AlyCoin</span>.</p>
                <p className="condition-paragraph">(4) En la medida en que <span>AlyCoin</span> ofrece programas informáticos (por ejemplo, <span>AlyWallet</span>) en su sitio web, el software debe utilizarse bajo su propio riesgo. <span>AlyCoin</span> no se responsabiliza por los daños resultantes de la instalación y / o uso del software de la sección de descarga, en la medida en que esté legalmente permitido. A pesar de los controles de virus actualizados, se excluye la responsabilidad por daños y perjuicios causados por virus informáticos como parte de las regulaciones legales. Además, <span>AlyCoin</span> no es responsable por problemas en la calidad del acceso al servicio debido a fuerza mayor o eventos por los cuales <span>AlyCoin</span> no tiene la culpa. Además, <span>AlyCoin</span> no es responsable de la adquisición no autorizada de sus datos personales por parte de terceros (por ejemplo, por un acceso no autorizado de "hackers" a la base de datos).</p>
                <p className="condition-paragraph">(5) <span>AlyCoin</span> no se hace responsable de los daños, independientemente de su naturaleza, causados por la pérdida de datos en los servidores de las computadoras, excepto en el caso de una conducta intencional o negligente de <span>AlyCoin</span>, sus empleados o agentes indirectos. <span>AlyCoin</span> no es responsable del contenido extranjero, al que se puede acceder mediante enlaces. Si <span>AlyCoin</span> detecta o recibe una notificación de que una oferta vinculada tiene contenido ilegal, este enlace se eliminará.</p>
                <p className="condition-paragraph">(6) <span>AlyCoin</span> no se responsabiliza de malas acciones realizadas por ejecutivos de ventas (<span>AlyExecutive</span>) de <span>AlyCoin</span>, como lo son ventas de paquetes de <span>AlyCoin</span> a un precio diferente del establecido por <span>AlyCoin</span> o faltas descritas en el punto 4 (1) de este contrato. No obstante, se compromete a cancelar las cuentas de quienes falten a estas regulaciones, que sean identificados por los usuarios.</p>
                <h6 className="condition-subtitle">7. Protección de datos</h6>
                <p className="condition-paragraph">(1) <span>AlyCoin</span> recopila y utiliza datos que usted comunica voluntariamente solo en el marco de las disposiciones legales. Las disposiciones detalladas para la protección de datos están disponibles en nuestras disposiciones sobre protección de datos</p>
                <h6 className="condition-subtitle">8. Misceláneo</h6>
                <h6 className="condition-subtitle-diff">a) Derechos de marca y derechos de autor.</h6>
                <p className="condition-paragraph">(1) <span>AlyCoin</span>, en su contexto, es el único titular de los derechos de copia, difusión, procesamiento y todos los derechos de autor, y el derecho a la transferencia y reproducción intangibles del sitio web de <span>AlyCoin</span> y de los contenidos individuales, servicios de otro tipo desarrollados. Servicios y derechos de protección. El uso de todos los servicios y los contenidos incluidos en él, los materiales, así como las marcas comerciales y los nombres comerciales (como, por ejemplo, el nombre de <span>AlyCoin</span> y el logotipo correspondiente) está permitido exclusivamente para los fines mencionados en estos Términos de uso. El uso sin la aprobación explícita de <span>AlyCoin</span> se considera una violación de estos Términos de uso y puede provocar el bloqueo o la eliminación de su perfil, incluidas todas las carteras y sus contenidos.</p>
                <p className="condition-paragraph">(2) Usted tiene todos los derechos sobre los contenidos cargados por usted (por ejemplo, en la Comunidad <span>AlySocial</span>) y es el único responsable. <span>AlyCoin</span> obtiene solo los derechos necesarios sobre estos contenidos en relación con la publicación y el uso de contenidos en la plataforma <span>AlyCoin</span>.</p>
                <p className="condition-paragraph">(3) <span>AlyCoin</span> procesará las violaciones contra los derechos de autor, derechos de marca registrada u otros derechos de autor complementarios, y <span>AlyCoin</span> se reserva el derecho de eliminar o desactivar contenidos para los cuales se informó de una infracción correspondiente, a su entera discreción, y de bloquear los perfiles de reinciden los ofensores.</p>
                <h6 className="condition-subtitle-diff">b) Precios y tarifas.</h6>
                <p className="condition-paragraph">(1) El registro y la creación de un perfil en <a target="_blank" href="www.alycoin.me">www.alycoin.me</a> es gratuito.</p>
                <p className="condition-paragraph">(2) El pago de los paquetes de <span>AlyCoin</span> adquiridos se recibirán por medio de Bitcoin (BTC), Ethereum (ETH), Litecoin (LTC), Dash (DASH), Monero (XMR) o Neo (NEO) a la wallet asignada según la criptomoneda elegida dentro del sitio web de <span>AlyCoin</span>. Usted deberá enviar la cantidad exacta reflejada en el cobro, asumiendo el costo de envío cobrado por su wallet. </p>
                <h6 className="condition-subtitle-diff">c) notificaciones y mensajes.</h6>
                <p className="condition-paragraph">Las notificaciones de <span>AlyCoin</span> se envían directamente a través de un mensaje en su perfil (Backoffice) o a la dirección de correo electrónico comunicada por usted en el momento de la inscripción. Usted es responsable de asegurarse de que sus datos de contacto estén siempre actualizados.</p>
                <h6 className="condition-subtitle-diff">d) Sin garantía / cambio, restricción de servicios de <span>AlyCoin</span> / transferencia a terceros</h6>
                <p className="condition-paragraph">(1) Su acceso al sitio web y los servicios de <span>AlyCoin</span> se realiza bajo su propio riesgo.</p>
                <p className="condition-paragraph">(2) <span>AlyCoin</span> tiene derecho a realizar cambios en el sitio web y los servicios ofrecidos en el ecosistema de <span>AlyCoin</span> sin ninguna indicación o responsabilidad previa.</p>
                <p className="condition-paragraph">(3) <span>AlyCoin</span> se reserva el derecho de restringir el uso de los servicios, incluida la posibilidad de contactar a otros miembros a través del sitio web, si <span>AlyCoin</span> considera que usted ha violado las obligaciones contractuales o ha utilizado los servicios de forma indebida.</p>
                <p className="condition-paragraph">(4) AlyCoin no garantiza</p>
                <p className="condition-paragraph">• Que es legal en el marco de la jurisdicción competente según su legislación nacional que usted utilice los servicios del ecosistema de <span>AlyCoin</span> o lo anuncie o participe en cualquier actividad de <span>AlyCoin</span></p>
                <p className="condition-paragraph">• Que el acceso al sitio web de <span>AlyCoin</span> funcione sin ningún error y esté libre de fallos, sea oportuno y seguro, y que se eliminen los fallos (consulte también la Cláusula 5 de los Términos de uso para esto)</p>
                <p className="condition-paragraph">• Que el material de capacitación u otra información sea completa, correcta o confiable</p>
                <p className="condition-paragraph">(5) <span>AlyCoin</span> se reserva el derecho de transferir, ceder, sublicenciar o comprometer todos los derechos y obligaciones de este contrato de usuario y las condiciones de uso de forma total o parcial a un tercero sin notificación previa, en la medida en que el tercero también cumpla con los requisitos aplicables, contractuales y otras leyes.</p>
                <h6 className="condition-subtitle-diff">e) Acuerdos con terceros.</h6>
                <p className="condition-paragraph">(1) <span>AlyCoin</span> realiza acuerdos con terceros de vez en cuando, que representan al proveedor de servicios externo y le proporcionan a <span>AlyCoin</span> y a usted el software / tecnología / TI para productos o servicios. Usted se compromete a cumplir con las condiciones y pautas de este tercero, en la medida en que se publiquen en el sitio web de <span>AlyCoin</span> o estén vinculados con el sitio web respectivo del tercero. Estos términos y pautas pueden cambiar en cualquier momento. Cada cambio será informado a usted en el anterior.</p>
                <h6 className="condition-subtitle-diff">f) Ley aplicable y jurisdicción</h6>
                <p className="condition-paragraph">(1) Su relación legal con AlyCoin está sujeta a la ley de la sede de <span>AlyCoin</span>. Las disposiciones obligatorias del país de su residencia habitual no se verán afectadas.</p>
                <p className="condition-paragraph">(2) Todas las disputas que surjan en relación con los servicios de <span>AlyCoin</span> están sujetas a la jurisdicción de la sede de AlyCoin. Las disposiciones obligatorias del país de su residencia habitual no se verán afectadas.</p>
                <p className="condition-paragraph">(3) En caso de ineficacia e incompleta de una cláusula de estos Términos de uso, todo el contrato no se vuelve ineficaz. Por el contrario, la cláusula inefectiva debe ser reemplazada por una nueva cláusula que sea efectiva, y se acerque más a la intención económica de la cláusula inefectiva. Lo mismo es aplicable para cerrar una brecha que requiere regulación.</p>
                <p className="condition-paragraph">(4) <span>AlyCoin</span> puede cambiar estos Términos de uso y la pauta de protección de datos en cualquier momento. Se le informará de cada cambio importante antes de que entre en vigencia en un formulario provisto para mensajes y notificaciones.</p>
                <p className="condition-paragraph">(5) Puede descargar los Términos de uso actualizados en cualquier momento como archivo PDF sin costo.</p>
            </div>
            <Footer />
        </div>
    )
}

export default Condition;